avae/data.py
=> 54 Removes unnecessary nested dirs during eval

avae/loss.py, avae/model_b.py, avae/train.py
=> 51 fix beta vae bug

avae/data.py, avae/vis.py
This full request addresses issues #50 and #35
=> Plot affinity

avae/loss.py
=> Add zero tensor to device when no affinity or gamma

avae/config.py, avae/train.py, configs/avae-test-config.yml, run.py
Fixes #20 
Could we give models a more meaningful name? 'a' and 'b' can be confusing.
=> Add option to choose model

avae/vis.py
Add check if plots directory already exists.
Also fix minor inconsistent capitalization.
Fixes #84 
Fixes #35
=> Fix affinity matrix plotting failure

avae/config.py, configs/avae-test-config.yml, run.py
=> 70 fix frequency controls

avae/vis.py
Preserves space when pulling from remote
Fixes #95
=> Separate dynamic from static plots

avae/vis.py
Change marker opacity, size, legend and axis font size.
Fixes #97
=> Change plots for clarity

avae/config.py, avae/evaluate.py, avae/train.py, avae/vis.py, configs/avae-test-config.yml, run.py, tests/test_train_eval_pipeline.py
Adding similarity matrix visualisation, for each epoch create a matrix of mean and standard deviation of the latent space similarity by the class labels for train and valid samples. 
E.g:
Mean (train - valid): 
Standard deviation (train - valid): 
TODO:
=> Model affinity vis

avae/train.py
so that accuracy is printed together with other metrics like loss.
=> Move state and vis down

avae/train.py, avae/vis.py, run.py
=> Fix CM labels and where we save the config yml file 

avae/evaluate.py
Same as PR #154 but for similarity matrix
=> Adding class order similarity evaluation

avae/train.py
=> Auto select state when restart activated but state isnt

.gitignore
Exclude .DS_Store in git
Trying to seem useful 😅
=> Update .gitignore to exclude DS_Store

tools/augment_mrcs.py
=> Add a preprocessing script to augment mrc files.

avae/data.py, avae/evaluate.py, avae/loss.py, avae/model_a.py, avae/train.py, avae/utils.py, avae/utils_learning.py, avae/vis.py
Fixes #203
Changelog:
- fix bug in batch feedback outside of batch loop (used to flush in print)
- move visualisation feedback from DEBUG to INFO so that we can track the ouputs produced by the code during execution
- text feedback has become unreadable - add whitespace to separate blocks of execution for better visual distinction
=> Fix bug in batch print and clean up execution feedback.

avae/utils.py
Prevents cluttering with log and config files.
=> Create a directory for configs

avae/data.py
=> Fix for unconditional rescale

avae/config.py, avae/evaluate.py, avae/train.py, configs/avae-test-config.yml
=> Fix failing default pose class disentanglement settings

avae/evaluate.py, avae/train.py, avae/utils.py, avae/vis.py
=> removed grid processing from pose_class_disentanglement_plot

avae/config.py, avae/evaluate.py, avae/train.py, avae/vis.py, tools/plotting_post_process.ipynb
Reverts alan-turing-institute/affinity-vae#286
=> Revert "Further post process"

avae/decoders/differentiable.py, avae/vis.py, run.py, tools/plotting_post_process.ipynb
Removes optional[int] from output_channel variable in differentiable decoder 
applies some changes to the post process notebook
=> Patch napari plugin

README.md, avae/config.py, avae/decoders/differentiable.py, avae/evaluate.py, avae/settings.py, avae/vis.py, run.py, tests/test_train_eval_pipeline.py, tests/test_vis.py, tools/plotting_post_process.ipynb
=> Pdf png file save
